package sudoku.cit260.group4.views;

import sudoku.controls.NewGameControl;
import sudoku.controls.MainMenuControl;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Jessica, Miquelyn, Jessica, Heidi
 */
public class PlayerNameFrame extends javax.swing.JFrame {

    private NewGameControl newGameCommands = null;
    /**
     * Creates new form EnterPlayerName
     */
    public PlayerNameFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpNameBody = new javax.swing.JPanel();
        jNameLable = new javax.swing.JLabel();
        jNameText = new javax.swing.JTextField();
        jNameButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Enter Player Name");

        jpNameBody.setBackground(new java.awt.Color(255, 153, 255));
        jpNameBody.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jNameLable.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jNameLable.setText("Please Enter Your Name:");

        jNameText.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N

        jNameButton.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        jNameButton.setText("Continue");
        jNameButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jNameButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpNameBodyLayout = new javax.swing.GroupLayout(jpNameBody);
        jpNameBody.setLayout(jpNameBodyLayout);
        jpNameBodyLayout.setHorizontalGroup(
            jpNameBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpNameBodyLayout.createSequentialGroup()
                .addGroup(jpNameBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpNameBodyLayout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpNameBodyLayout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jNameButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpNameBodyLayout.createSequentialGroup()
                .addGap(0, 57, Short.MAX_VALUE)
                .addComponent(jNameLable, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );
        jpNameBodyLayout.setVerticalGroup(
            jpNameBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpNameBodyLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jNameLable, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jNameButton)
                .addContainerGap(126, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpNameBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpNameBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    MainMenuControl mainMenuControl = new MainMenuControl();
    private void jNameButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jNameButtonMouseClicked
        this.mainMenuControl.newGame();
    }//GEN-LAST:event_jNameButtonMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jNameButton;
    private javax.swing.JLabel jNameLable;
    private javax.swing.JTextField jNameText;
    private javax.swing.JPanel jpNameBody;
    // End of variables declaration//GEN-END:variables
}

